### ISSUE TITLE
/x in RegEx breaks highlighting

### ISSUE THREAD

**Issue by Fank** [atom/language-perl#10]
```
my $asd = 'ASDA';
my $a = 'A';
$asd =~ s/$a/V/xg;
my $nowTheHighlightingIsBroken = 1;
```
![perl_regex_x](https://cloud.githubusercontent.com/assets/1900106/6481263/44aacbae-c25c-11e4-9057-09456815b90e.png)

info: http://perldoc.perl.org/perlre.html#/x

if you remove the `x` in `/xg` so it looks like `/g;` than its fine.

**Comment by pchaigno** [comment]
Weird, the bug is not happening with [GitHub's engine](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fatom%2Flanguage-perl%2Fmaster%2Fgrammars%2Fperl.cson&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FLOLCODE%2FLOLTracer.lol&code=my+%24asd+%3D+%27ASDA%27%3B%0D%0Amy+%24a+%3D+%27A%27%3B%0D%0A%24asd+%3D~+s%2F%24a%2FV%2Fgx%3B%0D%0Amy+%24nowTheHighlightingIsBroken+%3D+1%3B) (it's not using the same engine for regular expressions I think).

Does it happen too if you use `gx` instead of `xg`?

**Comment by Fank** [comment]
Yep
![perl_regex_x2](https://cloud.githubusercontent.com/assets/1900106/6483507/315aecc6-c272-11e4-9d06-9e9f9fcbf3c9.png)

**Comment by 50Wliu** [comment]
What version of Atom are you using?

**Comment by Fank** [comment]
latest 0.186.0

**Comment by pchaigno** [comment]
I was able to reproduce the issue in Atom. #11 should fix it.
