### ISSUE TITLE
Code after opening block quote (<<END) is treated as part of the quote

### ISSUE THREAD

**Issue by scoricov** [atom/language-perl#2]
![host pm - users bitman documents dev wz 2014-05-07 16-42-17 2014-05-07 16-44-40](https://cloud.githubusercontent.com/assets/318745/2935718/1b4b551a-d826-11e3-9334-b8f24e4b2622.jpg)

**Comment by Fank** [comment]
I tried to fix this but i can't find a "reset" option.
The "block" which highlight this is https://github.com/atom/language-perl/blob/master/grammars/perl.cson#L1090-L1109

The problem is that the `<<SQL_END ...... SQL_END` matches everything inside, if you remove following https://github.com/atom/language-perl/blob/master/grammars/perl.cson#L1097-L1098
it will look like:
![language-perl_5](https://cloud.githubusercontent.com/assets/1900106/6532167/d05eafe2-c43e-11e4-8f19-ed1bc8ebfac8.png)

But i can't enable perl highlighting between `<<SQL_END, <HERE>` until the line ends:
![langugage-perl12312312131](https://cloud.githubusercontent.com/assets/1900106/6534376/2f113eb0-c43f-11e4-8559-fcaf6dd308ee.png)

I tried following selector `((<<) *((?![=\\d\\$\\( ])[^;,\'"`\\s)]*))(.*)\\n?` to catch area which needs perl highlighting, but i didn't found a soloution to use parent highlighting or tell him to use "$self" aka "source.perl". Can someone tell me how to use different highlightings in different "regex groups"?
