### ISSUE TITLE
Hyperlik in RegEx match break highlighting

### ISSUE THREAD

**Issue by Fank** [atom/language-perl#46]
![screenshot from 2015-06-29 14 43 53](https://cloud.githubusercontent.com/assets/1900106/8408071/4f574420-1e6d-11e5-89cd-9ecf6cfe5ef3.png)

```perl
	if ($RedirectToURI) {
		$RedirectToURI = "http://$RedirectToURI" if $RedirectToURI !~ m~^http://~;
	}
	else {
		$RedirectToURI = '/';
	}
```

**Comment by Fank** [comment]
This issue does not came from the perl language package, but it effects it.
@kevinsawicki Where does this "markup" stuff came from?

e.g. `m~^http://~;` -> the "http" part will be get highlighted and break the whole highlighting.
![screenshot from 2015-06-29 20 32 58](https://cloud.githubusercontent.com/assets/1900106/8415364/857bd4cc-1e9e-11e5-998e-b373ffecb7f8.png)

**Comment by infininight** [comment]
It comes from atom/language-hyperlink, I'm currently looking into this issue for TextMate. I'm leaning toward just disabling the injection for regular expression strings since they are less likely to be valid URLs.

**Comment by Fank** [comment]
@infininight could you give me "detailed" instruction how to fix this issue?
Because I need such feature in other languages too.

**Comment by infininight** [comment]
There is an injection grammar in the language-hyperlink bundle that injects into `text, string, comment, source.gfm` currently. This allows matching urls and allowing enter to open them. It's enabled in strings to match things like the src attribute in an link tag in HTML and other such uses. But since you are unlikely to include a literal url in a regular expression it's probably a good idea to just exclude them. This can be done by making the injection selector `text, string -string.regexp, comment, source.gfm`.

**Comment by Fank** [comment]
Yea thanks for the info. I added the "exclude" to the injector and it worked fine.
